behaviors:
  RobotAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      # If you only have vector observations, this is enough.
      # If you later add cameras, you'll also configure visual_observation configs.
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    # Optional if you plan self-play later; for now we keep it simple
    # self_play:
    #   save_steps: 20000
    #   team_change: 100000
    #   swap_steps: 20000
    #   play_against_current_self_ratio: 0.5
    max_steps: 5.0e6
    time_horizon: 64
    summary_freq: 5000
    checkpoint_interval: 500000
    threaded: false